{
    "name": "Multi Branch Library Reporting",
    "version": "17.0.1.0.0",
    "category": "Addons",
    "summary": "Library is an addons for Odoo 17 to manage library",
    "description": """Library is an addons for Odoo 17 to manage library""",
    "author": "April",
    "company": "April Company",
    "maintainer": "ERP Team April Company",
    "depends": ["web", "mail", "base", "library_managed"],
    "data": [
        "security/ir.model.access.csv",
        "security/multi_library_report.xml",
        "views/multi_menu.xml",
        "views/multi_library_report.xml",
        "wizard/multi_library_wizard.xml",
    ],
    "assets": {},
    "installable": True,
    "auto-install": False,
    "license": "LGPL-3",
}
